version: "3.8"

services:
  db:
    image: postgres:15
    container_name: movieapp-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: alexis
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: movieapp
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
